/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import ReadFile.FileMap;
import ReadFile.ReadFiles;
import ReadFile.Tokenizer;
import Storage.MyFileDirectory;
import Storage.MyFileWithPosition;
import Storage.TernarySearchTrie;
import java.awt.CardLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JPanel;
import opennlp.tools.tokenize.TokenizerME;
import opennlp.tools.tokenize.TokenizerModel;

/**
 *
 * @author zhujinmeng
 */
public class LoadJPanel extends javax.swing.JPanel {

    public JPanel userProcessContainer;
    public TernarySearchTrie tst;
    /**
     * Creates new form LoadJPanel
     */
    public LoadJPanel(JPanel upc, TernarySearchTrie t) throws IOException, FileNotFoundException {
        initComponents();
        this.userProcessContainer = upc;
        this.tst = t;
        loadLabel.setText("");
        
    }
    
    
    public void loadData(TernarySearchTrie tst) throws IOException, FileNotFoundException{
        TokenizerModel model = Tokenizer.loadTokenizer();
        TokenizerME tokenizer = new TokenizerME(model);
        String[] tokens;
        ArrayList<FileMap> textList = ReadFiles.readAllFile(); 
        for(FileMap file : textList){
            int positionInOneFile = 1;
            tokens = tokenizer.tokenize(file.fileContent);
            for(String item : tokens){
                StringBuffer br = new StringBuffer();
                for(int i=0;i<item.length();i++){
                    char c = item.charAt(i);
                    br.append(String.valueOf(c).replaceAll("[^A-Za-z0-9]", "").toLowerCase());
                }
                if(!br.equals("")){
                    String pitt = br.toString();
                    if(!pitt.equals("")){
                        System.out.println(pitt);                   
                        if(tst.contains(pitt)){
                            boolean flag = false;
                            for(MyFileWithPosition m1 : tst.get(pitt).myFileList){
                                if(m1.fileName.equals(file.fileName)){
                                    m1.posList.add(positionInOneFile);
                                    flag = true;
                                }
                            }
                            if(!flag){
                                MyFileWithPosition m2 = new MyFileWithPosition(file.fileName);
                                m2.posList.add(positionInOneFile);
                                tst.get(pitt).myFileList.add(m2);
                            }                       
                        }else{
                            MyFileDirectory mfd = new MyFileDirectory();
                            MyFileWithPosition mfp = new MyFileWithPosition(file.fileName);
                            mfp.posList.add(positionInOneFile);
                            mfd.myFileList.add(mfp);
                            tst.put(pitt, mfd);                       
                        } 
                    }
                        positionInOneFile++;
                }  
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadLabel = new javax.swing.JLabel();
        beginButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        loadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadLabel.setText("Loading...");

        beginButton.setText("Begin");
        beginButton.setEnabled(false);
        beginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load Data");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(beginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(loadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(loadButton)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(loadButton)
                .addGap(106, 106, 106)
                .addComponent(loadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(beginButton)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void beginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginButtonActionPerformed
        // TODO add your handling code here:
        SearchJPanel ljp = new SearchJPanel(userProcessContainer, tst);
        userProcessContainer.add("SearchJPanel",ljp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_beginButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
       
        
        
        
        try{
            loadLabel.setText("Loading...");
            loadData(tst);
            loadButton.setEnabled(false);
            loadLabel.setText("Load Complete");
            beginButton.setEnabled(true);
       }catch(IOException ex){
           
       } 
        
    }//GEN-LAST:event_loadButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginButton;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel loadLabel;
    // End of variables declaration//GEN-END:variables
}
